sync-requests
vvrubel/molecad pull request #1
Opened 2021-06-17 10:32 UTC by vvrubel

NEW: general part of sync requests is called by single id (chunk - in progress)
`pubchem-sync-requests.ipynb` : ready to start but it will be lasting for 26000 hour

2021-06-18 13:50 UTC, churnikov requested changes

2021-06-18 13:50 UTC, churnikov commented on data/save_json.py
> +DATA_DIR = os.path.expanduser("~/PycharmProjects/moleCad/data")
Плохо завязываться на путь в системе
Лучше это в настройки приложения вынести, в частности, посмотри `.env`

2021-06-18 13:50 UTC, churnikov commented on data/save_json.py
> +def save_data(obj) -> str:
Документация
Входной тип

2021-06-18 13:50 UTC, churnikov commented on info/request_limit.md
> +- PubChem has a standard `time limit of 30 seconds per web service request`.
◀️ Папку можно `docs` назвать, так более стандартно

2021-06-18 13:50 UTC, churnikov commented on info/request_limit.md
> +- PubChem has a standard `time limit of 30 seconds per web service request`.
Кстати у тебя тут инфа дублируется с другим readme, тебе не кажется?

2021-06-18 13:50 UTC, churnikov commented on info/request_limit.md
> +>
```suggestion

```

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    #TODO make description
do todo?)

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    if domain == `assay`:
```suggestion
    if domain == ``compound``:
    if domain == ``substance``:
    if domain == ``assay``:
```

Мы пишем документацию в формате restuctured text. Лучше сразу к нему привыкать

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    :return: string is the second part of URL
Опечатка?
Звучит криво

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +        operation: str,
Моё мнение, что лучше такие штуки через enum делать

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    # TODO
Чик чик

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    :param output_format: takes a value from the
enum

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    pass
Либо убрать либо `raise NotImplementedError()`

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    pass
Нельзя такое оставлять

2021-06-18 13:50 UTC, churnikov commented on molecad/builder.py
> +    pass
![image](https://user-images.githubusercontent.com/8545082/122554237-691ea600-d041-11eb-93bc-c99e14ff745f.png)

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +        identifiers: Iterable[T],
```suggestion
        identifiers: Iterable[T], #< нафига?
```

```suggestion
        identifiers: Iterable[Any],
```

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +    # TODO
No
Допиши

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +def execute_request(url: str, params: dict[str, str]) -> dict[int, Any]:
```suggestion
def execute_request(url: str, params: Dict[str, str]) -> Dict[int, Any]:
```

Так не пойдёт для py3.8

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +    tags = ["MolecularFormula", "MolecularWeight", "IUPACName", "CanonicalSMILES"]
💩 
Очень плохо

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +    tags = ["MolecularFormula", "MolecularWeight", "IUPACName", "CanonicalSMILES"]
Мутабельные дефолтные переменные -- это плохо

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +    # # params = parser.parse_args(args)
```suggestion
```

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +            break
Логируй что не так пошло

```console
poetry add loguru
```

```suggestion
        except requests.HTTPError as e:
            logger.warning("Error occurred {}", e)
            break
```

Не надо проглатывать ошибки либо добавь комент почему

2021-06-18 13:50 UTC, churnikov commented on molecad/main.py
> +    print(t_run)
Добавишь логуру, замени на:

```suggestion
    logger.info("Download took {}", t_run)
```

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +) -> Generator[List[T], None, None]:
```suggestion
) -> Iterator[List[T]]:
```

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +) -> Generator[List[T], None, None]:
И везде поменяй

https://docs.python.org/3/library/typing.html#typing.Generator

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +    :param width: time window for counting requests
Из доки не понятно что это
И название переменной тоже плохое

Лучше что-то типа `delay` или `wait_time`, вообще не знаю как назвать

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +            del window[0]
```suggestion
            window.pop(0)
```

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +def request_data_json(url: str, **params: str) -> dict:
` **params: str` Подумай ещё

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +    :param params: dict of operation options as keys:value pairs
Если возможно, лучше вынести парамсы в как-то датакласс, чтобы было явно прописано, что можно передавать в апи (если можно)

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +    print(url)
Такие логи плохие
Надо больше информации добавлять
```suggestion
    logger.info("executing request {}", url)
```

2021-06-18 13:50 UTC, churnikov commented on molecad/sample_sync_requests.py
> +# TODO
Ась?

2021-06-18 13:50 UTC, churnikov commented on pyproject.toml
> +python = "^3.9"
окей, коменты выше про `dict` отменяются

2021-06-18 13:50 UTC, churnikov commented on pyproject.toml
> +mypy = "^0.902"
Это дев зависимости

2021-06-18 13:50 UTC, churnikov commented on pyproject.toml
> +secondary = true
Это не нужно

2021-06-18 13:50 UTC, churnikov commented on tests/test_molecad.py
>      assert __version__ == '0.1.0'
ты можешь версию брать из toml файла

Погугли как читать toml файлы из python

2021-06-18 19:29 UTC, vvrubel commented on data/save_json.py
> +def save_data(obj) -> str:
а как любой json проаннотировать? Dict[Any, Any]?

> Документация
> Входной тип
а как любой json аннотируется?

2021-06-18 19:32 UTC, vvrubel commented on info/request_limit.md
> +- PubChem has a standard `time limit of 30 seconds per web service request`.
> Кстати у тебя тут инфа дублируется с другим readme, тебе не кажется?

да я темой доков еще не занималась, поэтому она и называется info -> на будущее, чтобы не потерять оставила... я добавила в .gitignore ее в последних версиях коммитов, но видимо в старых она была и поэтому тут осталась

2021-06-18 19:42 UTC, vvrubel commented on molecad/sample_sync_requests.py
> +            del window[0]
а принципиальная разница есть?

2021-06-18 19:56 UTC, vvrubel commented on molecad/main.py
> +def execute_request(url: str, params: dict[str, str]) -> dict[int, Any]:
у меня ^3.9 в pyproject.toml указан

2021-06-18 20:03 UTC, vvrubel commented on molecad/sample_sync_requests.py
> +def request_data_json(url: str, **params: str) -> dict:
В документации написано, что **kwargs надо аннотировать типом значений этого дикта. Что здесь не так? 
![image](https://user-images.githubusercontent.com/53346960/122609743-27b0e980-d087-11eb-9016-05915ed58f78.png)

2021-06-18 20:04 UTC, vvrubel commented on pyproject.toml
> +python = "^3.9"
)))))

2021-06-18 20:05 UTC, vvrubel commented on pyproject.toml
> +mypy = "^0.902"
а это через поэтри надо сказать или просто тут переместить?

2021-06-18 20:05 UTC, vvrubel commented on pyproject.toml
> +secondary = true
кк

2021-06-18 20:36 UTC, vvrubel commented on tests/test_molecad.py
>      assert __version__ == '0.1.0'
это автогенерированный код)

2021-06-23 09:57 UTC, churnikov approved these changes
Парочка замечаний важна, думаю, сама поймёшь какие

И ещё раз перепроверь докстринги на грамматику, я мог что-то пропустить

После этого мерж

2021-06-23 09:57 UTC, churnikov commented on molecad/builder.py
> +    return ",".join(f'{i}' for i in args)
А почему не так?

```suggestion
    return ",".join(str(i) for i in args)
```

2021-06-23 09:57 UTC, churnikov commented on molecad/builder.py
> +    be passed, if only ``operation`` == "compound_property", "xrefs" or
А почему не обрабатывается это с выбросом ошибки?

2021-06-23 09:57 UTC, churnikov commented on molecad/builder.py
> +    :return: string is used as an argument invoking ``request_data()`` function
```suggestion
    :return: string which is used as an argument of ``request_data()`` function
```

2021-06-23 09:57 UTC, churnikov commented on molecad/builder.py
>      base = "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
Может это статичной переменной сделать на уровне модуля?

2021-06-23 09:57 UTC, churnikov commented on molecad/sample_sync_requests.py
> +            del window[0]
https://wemake-python-stylegui.de/en/latest/pages/usage/violations/best_practices.html#wemake_python_styleguide.violations.best_practices.WrongKeywordViolation

У меня нет больше особо аргументов, но интуитивно, pop делает ровно то, что ты хочешь, а del это ключевое слово, которое делает неявные операции. Лучше не привыкать его использовать, кмк

2021-06-23 09:57 UTC, churnikov commented on molecad/sample_sync_requests.py
> +    he function sends a synchronous "GET" request to the PUG REST service.
```suggestion
    Function sends a synchronous "GET" request to the PUG REST service.
```

2021-06-23 09:57 UTC, churnikov commented on molecad/sample_sync_requests.py
> +    :param url: string value was returned from ``build_url()`` function.
```suggestion
    :param url: string value returned from ``build_url()`` function.
```

2021-06-23 09:57 UTC, churnikov commented on tests/test_molecad.py
> +#         res = namespace_concatinator(prefix, suffix)
Убрать, либо явно пометь тест, что ему норм валиться

https://docs.pytest.org/en/latest/how-to/skipping.html

2021-06-23 13:22 UTC, vvrubel commented on molecad/builder.py
> +    be passed, if only ``operation`` == "compound_property", "xrefs" or
а я это пока не допилила, там в принципе если операция не из тех трех, то все ок, но нам нужна из тех трех

2021-06-23 13:23 UTC, vvrubel commented on molecad/builder.py
> +    be passed, if only ``operation`` == "compound_property", "xrefs" or
> А почему не обрабатывается это с выбросом ошибки?

а я это пока не допилила, там в принципе если операция не из тех трех, то все ок, но нам нужна из тех трех

2021-06-23 13:24 UTC, vvrubel commented on molecad/builder.py
>      base = "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
> Может это статичной переменной сделать на уровне модуля?

в начале так и было, просто по сути ее только эта функция использует, поэтому я хз как лучше. А как принято?

2021-06-23 13:31 UTC, churnikov commented on molecad/builder.py
>      base = "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
Я бы всё равно вынес на уровень модуля хотя бы

Вообще, я использую такую штуку последнее время:
https://pydantic-docs.helpmanual.io/usage/settings/

2021-06-23 13:40 UTC, vvrubel commented on molecad/builder.py
> +    return ",".join(f'{i}' for i in args)
> А почему не так?

для Emun: у `f'{...}'` под капотом `format()`
ну и вроде f-strings быстрее
```
In [1]: from enum import Enum

In [2]: class X(str, Enum):
   ...:     X = 'x'
   ...:
   ...: print(str(X.X))
   ...: print(format(X.X))
   ...: print(f'{X.X}')
X.X
x
x
```

2021-06-28 21:49 UTC, churnikov requested changes

2021-06-28 21:49 UTC, churnikov commented on .gitignore
> +config.py
Nope
Посмотри в эту сторону https://pydantic-docs.helpmanual.io/usage/settings/

И как работать с .env файлами
Например в molprop-back как сделано

2021-06-28 21:49 UTC, churnikov commented on molecad/data_handler.py
> +def main(inp_file: Path, out_dir: Path, maxsize: int = 1000):
Только у тебя не реальные пути на вход, а строки

Смотри тогда сюда
https://pypi.org/project/click-pathlib/

2021-06-28 21:49 UTC, churnikov commented on molecad/db_import.py
> +The example with all required fields is named ``config.example.py``.
Я бы добавил пометку о том, что все данные из базы будут удалены

2021-06-28 21:49 UTC, churnikov commented on molecad/pubchem_requests.py
> +) -> Generator[int, None, None]:
Почему не `Iterator[int]`?

2021-06-28 21:49 UTC, churnikov commented on molecad/pubchem_requests.py
> +    tags = [
Никаких мутабельных значений по умолчанию!

2021-06-28 21:49 UTC, churnikov commented on molecad/pubchem_requests.py
> +    ]
```suggestion
    tags = (
        PropertyTags.MOLECULAR_FORMULA,
        PropertyTags.MOLECULAR_WEIGHT,
        PropertyTags.CANONICAL_SMILES,
        PropertyTags.INCHI,
        PropertyTags.IUPAC_NAME,
        PropertyTags.XLOGP,
        PropertyTags.H_BOND_DONOR_COUNT,
        PropertyTags.H_BOND_ACCEPTOR_COUNT,
        PropertyTags.ROTATABLE_BOND_COUNT,
        PropertyTags.ATOM_STEREO_COUNT,
        PropertyTags.BOND_STEREO_COUNT,
        PropertyTags.VOLUME_3D,
    )
```

2021-06-28 21:49 UTC, churnikov commented on molecad/pubchem_requests.py
> +                # logger.info("Data saved in {}", file)
```suggestion
```

2021-06-28 21:49 UTC, churnikov commented on molecad/pubchem_requests.py
> +                # logger.info("Data saved in {}", file)
Не привыкай сохранять комментарии

2021-06-28 21:49 UTC, churnikov commented on molecad/url_builder.py
> +from .types_ import (
Кажется, ты применяла isort, а сейчас забила

2021-06-28 21:49 UTC, churnikov commented on molecad/url_builder.py
> +    :param domain: must be a string and refers to database - compound |
Кажется, можно чуть поменять эту строку, сославшись на ``Domain``

2021-06-29 10:30 UTC, vvrubel commented on molecad/db_import.py
> +The example with all required fields is named ``config.example.py``.
> Я бы добавил пометку о том, что все данные из базы будут удалены

по-хорошему надо назначать _id, которое = CID, если его нет, то добавлять, а если есть, то бросать duplicate key error (но на это надо время потратить) как лучше?

2021-06-29 10:30 UTC, vvrubel commented on molecad/data_handler.py
> +def main(inp_file: Path, out_dir: Path, maxsize: int = 1000):
> Только у тебя не реальные пути на вход, а строки
> 
> Смотри тогда сюда
> https://pypi.org/project/click-pathlib/

затупила. сделаю строки? тем более, что с помощью pathlib их путями делаю

2021-06-29 10:30 UTC, vvrubel commented on molecad/pubchem_requests.py
> +) -> Generator[int, None, None]:
потому что у него есть yield и генератор более строгий тип. Ну, его можно назвать и итератором, но зачем?

2021-06-29 10:30 UTC, vvrubel commented on molecad/pubchem_requests.py
> +    tags = [
ес сэр!

2021-06-29 10:30 UTC, vvrubel commented on molecad/pubchem_requests.py
> +                # logger.info("Data saved in {}", file)
> Не привыкай сохранять комментарии

упс, забыла убрать следы экспериментов...

2021-06-29 10:30 UTC, vvrubel commented on molecad/url_builder.py
> +from .types_ import (
> Кажется, ты применяла isort, а сейчас забила

ты прав, только не забила, а забыла включить..
UPD: хотя нет, он включен...

2021-06-29 12:12 UTC, churnikov commented on molecad/data_handler.py
> +def main(inp_file: Path, out_dir: Path, maxsize: int = 1000):
А чего не click-pathlib?

2021-06-29 12:12 UTC, churnikov commented on molecad/db_import.py
> +The example with all required fields is named ``config.example.py``.
Я тебе предлагаю описать нюанс того, как оно сейчас работает и всё)

2021-06-29 12:12 UTC, churnikov commented on molecad/pubchem_requests.py
> +) -> Generator[int, None, None]:
Потому что они эквиваленты на уровне того, как ты пользуешься типом генератор.
Зачем усложнять? Напиши просто Iterator[int]. Это понятнее и проще

2021-06-29 12:12 UTC, churnikov commented on molecad/url_builder.py
> +from .types_ import (
Скорее всего, проблема в настройке isort
Добавь тогда просто комент, что не работает, сорян

2021-07-06 13:49 UTC, closed without merging