Sync rebase
vvrubel/molecad pull request #2
Opened 2021-07-05 18:28 UTC by vvrubel

2021-07-05 21:29 UTC, churnikov requested changes
Зачем всё пихать в один ПР?
Он такой огромный, что его не возможно смотреть, бей его на более маленькие.

Я не буду смотреть дальше error_handlers.py

2021-07-05 21:29 UTC, churnikov commented on molecad/data/console/__main__.py
> +    type=pathlib.Path,
Оно точно работает?

2021-07-05 21:29 UTC, churnikov commented on molecad/data/core/db.py
> +class Connect(object):
```suggestion
class Connect:
```

2021-07-05 21:29 UTC, churnikov commented on molecad/data/core/db.py
> +class Connect(object):
Почему не просто функция?

2021-07-05 21:29 UTC, churnikov commented on molecad/data/script.example.sh
> +#!/bin/sh
Почему про этот скрипт нигде не написано?
Либо удалить либо написать, как использовать

2021-07-06 09:45 UTC, vvrubel reviewed
@churnikov у меня не получится отменить кометы так, чтобы пр разделился на несколько логичных частей: надо либо еще один пр и по очереди их коммитить (причем получится криво-косо, тк импорты), либо досмотреть так, потому что на самом деле все новое - выше error-handler, а остальное либо по шаблону сделано, либо из предыдущего пр взято

2021-07-06 09:45 UTC, vvrubel commented on molecad/data/core/db.py
> +class Connect(object):
> Почему не просто функция?

взяла из гайда
https://docs.mongodb.com/guides/server/insert/

2021-07-06 09:45 UTC, vvrubel commented on molecad/data/console/__main__.py
> +    type=pathlib.Path,
> Оно точно работает?

c 8 версии, да
у меня его кст не было в pyproject.toml но я добавила

2021-07-06 09:45 UTC, vvrubel commented on molecad/data/script.example.sh
> +#!/bin/sh
> Почему про этот скрипт нигде не написано?
> Либо удалить либо написать, как использовать

собственно это в сегодняшних планах

2021-07-14 08:00 UTC, vvrubel commented
сделали 4 отдельных pr: #3 – #6 вместо одного #2

2021-07-14 08:00 UTC, closed without merging