merge master(parent-> improvements) to mongo-rdkit
vvrubel/molecad pull request #9
Opened 2021-07-14 07:56 UTC by vvrubel

Этот pr будет о том как смержила ветку mongo-rdkit и improvements

2021-07-14 08:50 UTC, churnikov requested changes

2021-07-14 08:50 UTC, churnikov commented on .env.sample
> +MONGO_TEST_SCHEMA_COLLECTION=""
А
Что?
Почему так?

Если хочешь другие значения для тестирования использовать, то просто другой .env файл используй

2021-07-14 08:50 UTC, churnikov commented on README.md
> +`pyenv` наиболее безболезненно – читайте [тут](https://confluence.biocad.ru/x/vi1QCw).
```suggestion
`pyenv` наиболее безболезненно – читайте [тут](https://confluence.biocad.ru/x/vi1QCw).
```

2021-07-14 08:50 UTC, churnikov commented on molecad/data/console/cli.py
> +@pubchem_to_db.command(
Ох уж эти мелкие рефакторинги

2021-07-14 08:50 UTC, churnikov commented on molecad/data/db.py
> +    # index_lst = substructure.SubSearchNaive(q_mol, rdkit_schema, chirality=False)
.

2021-07-14 08:50 UTC, churnikov commented on molecad/data/db.py
> +    main()
Тянет на тест кейс
Но забей сейчас

2021-07-14 08:50 UTC, churnikov commented on molecad/data/downloader.py
> +    :param ids: Последовательность из значений одинакового типа, которые интерпретируются как
Почему так сильно поменялось
Тут есть что-то важное?

2021-07-14 08:50 UTC, churnikov commented on molecad/main.py
> +    return search(smiles)[skip:][:limit]
Если эта ручка ещё не актуальна, то убери этот код вообще отсюда

2021-07-14 10:26 UTC, vvrubel commented on .env.sample
> +MONGO_TEST_SCHEMA_COLLECTION=""
> А
> Что?
> Почему так?
> 
> Если хочешь другие значения для тестирования использовать, то просто другой .env файл используй

а есть где посмотреть, как settinngs.py примерно будет выглядеть с двумя .env файлами?

2021-07-14 10:29 UTC, vvrubel commented on README.md
> +`pyenv` наиболее безболезненно – читайте [тут](https://confluence.biocad.ru/x/vi1QCw).
> Suggested change 
> `pyenv` наиболее безболезненно – читайте [тут](https://confluence.biocad.ru/x/vi1QCw).  
> `pyenv` наиболее безболезненно – читайте [тут](https://confluence.biocad.ru/x/vi1QCw).

ты пробел убрал?

2021-07-14 10:30 UTC, vvrubel commented on molecad/data/console/cli.py
> +@pubchem_to_db.command(
> Ох уж эти мелкие рефакторинги

каюсь...

2021-07-14 10:35 UTC, vvrubel commented on molecad/data/downloader.py
> +    :param ids: Последовательность из значений одинакового типа, которые интерпретируются как
> Почему так сильно поменялось
> Тут есть что-то важное?

было много функций, которые делали одно и тоже, и затрудняли понимание кода на мой взгляд, я их сжала в одну. Только почему-то git не показывает удаленные кроме докстрингов у меня..

2021-07-14 10:35 UTC, vvrubel commented on molecad/main.py
> +    return search(smiles)[skip:][:limit]
> Если эта ручка ещё не актуальна, то убери этот код вообще отсюда

ок

2021-07-14 10:56 UTC, churnikov commented on .env.sample
> +MONGO_TEST_SCHEMA_COLLECTION=""
Ты можешь менять в тестах на нужный .env файл, как описано в пункте 2
https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support

2021-07-14 10:56 UTC, churnikov commented on README.md
> +`pyenv` наиболее безболезненно – читайте [тут](https://confluence.biocad.ru/x/vi1QCw).
Да
Это видно по этой фиговине
Удалено 2 пробела
<img width="92" alt="image" src="https://user-images.githubusercontent.com/8545082/125610742-be430fa1-5f7b-44b4-b4ad-81fb49fa0140.png">

2021-07-14 10:56 UTC, churnikov commented on molecad/data/db.py
> +    # index_lst = substructure.SubSearchNaive(q_mol, rdkit_schema, chirality=False)
Ну ты поняла, да?)

2021-07-14 10:56 UTC, churnikov commented on molecad/data/downloader.py
> +    :param ids: Последовательность из значений одинакового типа, которые интерпретируются как
Понятно

2021-07-14 10:56 UTC, churnikov commented on molecad/data/downloader.py
> +    #TODO
А что за TODO?

2021-07-14 11:17 UTC, vvrubel reviewed
скоро будет коммит

2021-07-14 11:17 UTC, vvrubel commented on molecad/data/downloader.py
> +    #TODO
> А что за TODO?

тоже забыла убрать заметку

2021-07-14 11:17 UTC, vvrubel commented on molecad/data/db.py
> +    # index_lst = substructure.SubSearchNaive(q_mol, rdkit_schema, chirality=False)
> Ну ты поняла, да?)

ды

2021-07-16 16:24 UTC, churnikov approved these changes
Можешь забить на коменты, если что
Время поджимает

2021-07-16 16:24 UTC, churnikov commented on README.md
> +  --setup [PROD|DEV]  Опция, позволяющая выбирать конфигурационный файл,
```suggestion
  --env [PROD|DEV]  Опция, позволяющая выбирать конфигурационный файл,
```

Принято так это называть

2021-07-16 16:24 UTC, churnikov commented on molecad/cli.py
> +    "указать опцию --prod/--dev для выбора рабочей базы.",
Ошибка

2021-07-16 16:24 UTC, churnikov commented on molecad/validator.py
> +def check_smiles(smiles) -> None:
Тип

2021-07-16 17:09 UTC, merged